development: &default
  adapter: postgresql
  database: connective
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: connective_test

production:
  <<: *default
  database: connective_prod
